[project]
name = "dikkiedict"
version = "0.1.0"
description = "Make it easy to implement conversion from and to dict-like types."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pyright>=1.1.393",
    "pytest>=8.3.4",
    "ruff>=0.9.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
extend-exclude = [
    "**/__pycache__/",
    "**/.egg-info/",
    "**/.pytest_cache/",
    "**/.ruff_cache/",
    "**/.venv/",
    ".git/",
]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D106", # Missing docstring in public nested class
    "D107", # Missing docstring in __init__
    "SIM108", # Use the ternary operator
]
select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "D",   # pydocstyle https://www.pydocstyle.org/en/stable/error_codes.html
    "E",   # pycodestyle
    "F",   # Pyflakes
    "I",   # isort
    "PT",  # flake8-pytest-style
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["D"]
"*.ipynb" = ["D"]

[tool.pyright]
typeCheckingMode = "strict"
reportPrivateImportUsage = "none" # some libraries do not properly re-export their types, see https://github.com/microsoft/pyright/issues/2639
exclude = [
    "**/__pycache__/",
    "**/.egg-info/",
    "**/.pytest_cache/",
    "**/.ruff_cache/",
    "**/.venv/",
    ".git/",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--strict-markers",
]
markers = ["slow"]
log_level = "INFO"
filterwarnings = [
]
testpaths = ["src", "tests"]
python_functions = ["test_*"]
