on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: ruff check
        run: uv run -- ruff check --output-format=github

      - name: ruff format
        run: uv run -- ruff format --check
        if: ${{ !cancelled() }}

      - name: pyright
        run: uv run -- pyright
        if: ${{ !cancelled() }}

      - name: pytest
        run: uv run -- pytest
        if: ${{ !cancelled() }}
